name: SudoSigns-OG
version: '${version}' 
authors: [ MylesMor, NotAlexNoyle ]
main: dev.mylesmor.sudosigns.SudoSigns
softdepend: [Multiverse-Core, Vault]
api-version: '${apiVersion}'
commands:
  sudosigns:
    description: Opens the SudoSigns-OG help menu.
    aliases: [sudosign, ss]
